#!/bin/bash

#-- UTILITY FUNCTIONS For Ubuntu ------------------------------------------------------
#list of functions herein:
#   ispackage_installed()
#   unTar()

#global variables used by this script:


#Code -----------------------------------------
echo "Sourcing Ubuntu Related Auxiliary functions..."


#FUNCTIONS ------------------------------------------------------------------------------

#is package installed
#usage: ispackage_installed package_name
#NOTE: This function must always exist!
function ispackage_installed()
{
  set +e
  DPKGRESULTTMP=`dpkg-query -W -f='${Status}\n' $1 2>&1 | grep -e "not-installed" -e "No packages found" -e "deinstall"`
  if [ "x$DPKGRESULTTMP" == "x" ]; then
    return 0
  else
    return 1
  fi
  unset DPKGRESULTTMP
  set -e
}

#usage: unTar format_z_j_lzma file_path files_to_extract
#NOTE: This function must always exist!
function unTar()
{
  TAR_OPT=$1
  TAR_FILE="$2"

  #TODO: option "-n" in "pv" will allow the usage of "dialog --gauge" :)
  case $TAR_OPT in
  z | j)
    pv $TAR_FILE | tar -x$TAR_OPT $*
    ;;
  *)
    pv $TAR_FILE | tar --$TAR_OPT -x $*
    ;;
  esac
}
