#!/bin/bash
#-----------------------------------------------------------------------
#   Nucleation - Nucleation (an unofficial OpenFOAM Installer) lower
#the work to have foam in your system.
#
#   visit: http://code.google.com/p/nucleation/
#
#-----------------------------------------------------------------------
#    This file is part of Nucleation.
#
#    Nucleation is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Nucleation is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Nucleation.  If not, see <http://www.gnu.org/licenses/>.
#-----------------------------------------------------------------------

#-- UTILITY FUNCTIONS For Ubuntu ------------------------------------------------------
#list of functions herein:
#   ispackage_installed()
#   unTar()

#global variables used by this script:


#Code -----------------------------------------
echo "Sourcing Ubuntu Related Auxiliary functions..."


#FUNCTIONS ------------------------------------------------------------------------------

#is package installed
#usage: ispackage_installed package_name
#NOTE: This function must always exist!
function ispackage_installed()
{
  set +e
  DPKGRESULTTMP=`dpkg-query -W -f='${Status}\n' $1 2>&1 | grep -e "not-installed" -e "No packages found" -e "deinstall"`
  if [ "x$DPKGRESULTTMP" == "x" ]; then
    return 0
  else
    return 1
  fi
  unset DPKGRESULTTMP
  set -e
}

#usage: unTar format_z_j_lzma file_path files_to_extract
#NOTE: This function must always exist!
function unTar()
{
  TAR_OPT=$1
  TAR_FILE="$2"
  shift 2

  #TODO: option "-n" in "pv" will allow the usage of "dialog --gauge" :)
  case ${TAR_OPT} in
  z | j)
    pv ${TAR_FILE} 2>&4 | tar -x${TAR_OPT} $*
    ;;
  *)
    pv ${TAR_FILE} 2>&4 | tar --${TAR_OPT} -x $*
    ;;
  esac
}
