#!/bin/bash

#-- USER INTERFACE FUNCTIONS ------------------------------------------------------
#list of functions herein:
#   define_system_custom_optionals()

#global variables used by this script:
#   INST_SYSTEM - System variant for installation - defined in the master script
#   DOUPGRADE   - option for using upgrade in apt-get - defined by define_system_custom_optionals()


#Code -----------------------------------------
echo "Sourcing User Interface functions for Ubuntu..."


#NOTE: This function must always exist!
function define_system_custom_optionals()
{
  if [ "x$CUSTOMOPTS_OFOPTIONALS" == "xon" ]; then
    #Settings choosing Dialog
    while : ; do
      SETTINGSOPTS=$(dialog --stdout --separate-output \
      --backtitle "$GUI_BACKTITLE"         \
      --checklist "Choose Ubuntu related settings: < Space to select ! >" 15 50 1 \
      1 "Do apt-get upgrade" $DOUPGRADE )

      if [ x"$?" == x"0" ]; then
        break;
      else
        cancel_installer
      fi
    done

    #Take care of unpack settings from SETTINGSOPTS
    DOUPGRADE=off
    for setting in $SETTINGSOPTS ; do
      if [ $setting == 1 ] ; then DOUPGRADE=on ; fi
    done
  fi
}
