#!/bin/bash
#-----------------------------------------------------------------------
#   Nucleation - Nucleation (an unofficial OpenFOAM Installer) lower
#the work to have foam in your system.
#
#   visit: http://code.google.com/p/nucleation/
#
#-----------------------------------------------------------------------
#    This file is part of Nucleation.
#
#    Nucleation is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Nucleation is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Nucleation.  If not, see <http://www.gnu.org/licenses/>.
#-----------------------------------------------------------------------

#-- USER INTERFACE FUNCTIONS ------------------------------------------------------
#list of functions herein:
#   define_system_custom_optionals()

#global variables used by this script:
#   INST_SYSTEM - System variant for installation - defined in the master script
#   DOUPGRADE   - option for using upgrade in apt-get - defined by define_system_custom_optionals()


#Code -----------------------------------------
echo "Sourcing User Interface functions for Generic System..."


#NOTE: This function must always exist!
function define_system_custom_optionals()
{
  if [ "x$CUSTOMOPTS_OFOPTIONALS" == "xon" ]; then
    #Nothing to do...
    :
  fi
}
