#!/bin/bash

#-- FIXING FUNCTIONS For Ubuntu ------------------------------------------------------
#list of functions herein:

#global variables used by this script:


#Code -----------------------------------------
echo "Sourcing patching functions for OpenFOAM ${OF_LONG_VERSION}, specific to Ubuntu..."

#-- FUNCTIONS -----------------------------------------------------

#Apply fixes associated with the system
#NOTE: This function must always exist!
function apply_fixes_system()
{
  if [ "x$USE_OF_GCC" == "xon" ]; then
    #this depends on the existing Ubuntu version
    link_gcc_libraries_to_system
  fi
}

function link_gcc_libraries_to_system()
{
  #Define which folder to fix libraries
  #[ "$SYSTEM_VERSION" != "8.04" ]
  if isleftlarger_or_equal $SYSTEM_VERSION 9.10 then
    if [ "$arch" == "x64" ]; then
      LIBRARY_PATH_TO_FIX=${PATHOF}/ThirdParty-1.6/gcc-$GCC_VERSION/platforms/linux64/lib64
    elif [ "$arch" == "x86" ]; then
      LIBRARY_PATH_TO_FIX=${PATHOF}/ThirdParty-1.6/gcc-$GCC_VERSION/platforms/linux/lib
    fi

    echo "-----------------------------------------------------"
    echo "Fixing library links"
    cd $LIBRARY_PATH_TO_FIX
    mv libstdc++.so.6 libstdc++.so.6.orig
    ln -s `locate libstdc++.so.6.0 | grep "^/usr/lib" | head -n 1` libstdc++.so.6
    mv libgcc_s.so.1 libgcc_s.so.1.orig
    ln -s `locate libgcc_s.so. | grep "^/lib" | head -n 1` libgcc_s.so.1
    echo "Fix up done"
    echo "------------------------------------------------------"
  fi
}

