#!/bin/bash

#-- USER INTERFACE FUNCTIONS ------------------------------------------------------
#list of functions herein:

#global variables used by this script:
#   INST_SYSTEM - System variant for installation - defined in the master script

#Code -----------------------------------------
echo "Sourcing Main functions functions for OpenFOAM 1.6.x and Ubuntu..."

