#!/bin/bash

#-- USER INTERFACE FUNCTIONS ------------------------------------------------------
#list of functions herein:
#     check_options_sanity_for_system()

#global variables used by this script:
#   INST_SYSTEM - System variant for installation - defined in the master script

#Code -----------------------------------------
echo "Sourcing Main functions functions for OpenFOAM 1.6.x and Ubuntu..."

