#!/bin/bash

#-- USER INTERFACE FUNCTIONS ------------------------------------------------------
#list of functions herein:

#global variables used by this script:
#   INST_SYSTEM - System variant for installation - defined in the master script

#Code -----------------------------------------
echo "Sourcing Main functions functions for OpenFOAM 1.6.x and Ubuntu..."

#Define files (including paths) to the files this script provides for of$OF_SHORT_VERSION/system
function define_script_s_files_ofv_system()
{
  #Nothing to do for now...
  :
}
