#!/bin/bash

#-- PATCHING FUNCTIONS For Ubuntu ------------------------------------------------------
#list of functions herein:

#global variables used by this script:


#Code -----------------------------------------
echo "Sourcing patching functions for OpenFOAM ${OF_LONG_VERSION}, specific to Ubuntu..."

#-- FUNCTIONS -----------------------------------------------------
