#!/bin/bash

#-- PATCHING FUNCTIONS For Ubuntu ------------------------------------------------------

echo "Sourcing patching functions for OpenFOAM 1.6.x, specific to Ubuntu..."

#-- FUNCTIONS -----------------------------------------------------
