#!/bin/bash

#-- FIXING FUNCTIONS For Ubuntu ------------------------------------------------------
#list of functions herein:

#global variables used by this script:


#Code -----------------------------------------
echo "Sourcing patching functions for OpenFOAM ${OF_LONG_VERSION}, specific to Ubuntu..."

#-- FUNCTIONS -----------------------------------------------------

#Apply fixes associated with the system
#NOTE: This function must always exist!
function apply_fixes_system()
{
  if [ "x$USE_OF_GCC" == "xon" ]; then
    #this depends on the existing gcc system version
    link_gcc_libraries_to_system
  fi
}

function link_gcc_libraries_to_system()
{
  #Nothing to do for 1.7.x
  :
}
