#!/bin/bash

#-- FIXING FUNCTIONS For Ubuntu ------------------------------------------------------
#list of functions herein:

#global variables used by this script:


#Code -----------------------------------------
echo "Sourcing patching functions for OpenFOAM ${OF_LONG_VERSION}, specific to Ubuntu..."

#-- FUNCTIONS -----------------------------------------------------

#Apply fixes associated with the system
#NOTE: This function must always exist!
function apply_fixes_system()
{
  #nothing to do, I guess...
  :
}
