#!/bin/bash
#-----------------------------------------------------------------------
#   Nucleation - Nucleation (an unofficial OpenFOAM Installer) lower
#the work to have foam in your system.
#
#   visit: http://code.google.com/p/nucleation/
#
#-----------------------------------------------------------------------
#    This file is part of Nucleation.
#
#    Nucleation is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Nucleation is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Nucleation.  If not, see <http://www.gnu.org/licenses/>.
#-----------------------------------------------------------------------

#-- USER INTERFACE FUNCTIONS ------------------------------------------------------
#list of functions herein:

#global variables used by this script:
#   INST_SYSTEM - System variant for installation - defined in the master script

#Code -----------------------------------------
echo "Sourcing Main functions functions for OpenFOAM $OF_LONG_VERSION and Ubuntu..."

#Define files (including paths) to the files this script provides for of$OF_SHORT_VERSION/system
#NOTE: This function must always exist!
function define_script_s_files_ofv_system()
{
  #Nothing to do for now...
  :
}

#also define files pertinent to each system
#NOTE: This function must always exist!
function define_packages_to_download_system()
{
  if [ "$arch" == "x64" ]; then
    #CMake is needed for old and new Ubuntu versions...
    #TODO: have to define that we have to build a cmake...
    :
#     if isleftlarger_or_equal 8.04 $SYSTEM_VERSION || isleftlarger_or_equal $SYSTEM_VERSION 10.04; then
#       THIRDPARTY_BIN_CMAKE="ThirdParty-1.6.linuxGcc.gtgz"
#     fi
  fi
}

#It will request any fixes deemed necessary to gcc after it is built
#NOTE: This function must always exist!
function fix_gcc_if_necessary()
{
  #Nothing to do
  :
}
