#!/bin/bash
#-----------------------------------------------------------------------
#   Nucleation - Nucleation (an unofficial OpenFOAM Installer) lower
#the work to have foam in your system.
#
#   visit: http://code.google.com/p/nucleation/
#
#-----------------------------------------------------------------------
#    This file is part of Nucleation.
#
#    Nucleation is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Nucleation is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Nucleation.  If not, see <http://www.gnu.org/licenses/>.
#-----------------------------------------------------------------------

#-- FIXING FUNCTIONS ------------------------------------------------------
#list of functions herein:

#global variables used by this script:
#   INST_SYSTEM - System variant for installation - defined in the master script
#   SCRIPT_WORKFOLDER - the folder where the main script's dependency files are located
#   OF_SHORT_VERSION - the short version of OpenFOAM to be installed. Example: 16x
#   OF_LONG_VERSION - the long version of OpenFOAM to be installed. Example: 1.6.x

#Code -----------------------------------------
echo "Sourcing fixing functions for OpenFOAM ${OF_LONG_VERSION}..."

#source system related script
if [ "x$INST_SYSTEM" != "x" -a "x$OF_SHORT_VERSION" != "x" ]; then
  . ${SCRIPT_WORKFOLDER}/${OF_MODULE_NAME}/${INST_SYSTEM}/fixes
else
  echo "The variable INST_SYSTEM and/or OF_SHORT_VERSION is/are empty and both are crucial to exist! Aborting execution."
  exit 1
fi

#-- FUNCTIONS -----------------------------------------------------

#FIXES ------
#NOTE: This function must always exist!
function apply_fixes()
{
  #fix the tutorials
  fix_tutorials

  cd_openfoam #this is a precautionary measure

  #fix ParaView's help file reference, for when ParaView isn't built
  if [ "x$BUILD_PARAVIEW" == "xoff" ]; then
    cd_openfoam
    if [ "$arch" == "x86" ]; then
      cd ThirdParty-1.6/paraview-3.6.1/platforms/linuxGcc/bin
    elif [ "$arch" == "x64" ]; then
      cd ThirdParty-1.6/paraview-3.6.1/platforms/linux64Gcc/bin
    fi
    if [ ! -e pqClientDocFinder_orig.txt ]; then cp pqClientDocFinder.txt pqClientDocFinder_orig.txt; fi
    if [ -e pqClientDocFinder_orig.txt ]; then cp pqClientDocFinder_orig.txt pqClientDocFinder.txt; fi
    sed -i -e 's=/home/dm2/henry/OpenFOAM='${PATHOF}'=' pqClientDocFinder.txt
  fi

  #apply fixes associated with the system
  apply_fixes_system
}

