#!/bin/bash

#-- UTILITY FUNCTIONS For Ubuntu ------------------------------------------------------
#list of functions herein:
#   ispackage_installed()
#   unTar()

#global variables used by this script:


#Code -----------------------------------------
echo "Sourcing SuSE Related Auxiliary functions..."


#FUNCTIONS ------------------------------------------------------------------------------

#is package installed
#usage: ispackage_installed package_name
#NOTE: This function must always exist!
function ispackage_installed()
{
  set +e
  DPKGRESULTTMP=`rpm -qa | grep "$1"`
  if [ "x$DPKGRESULTTMP" == "x" ]; then
    return 1
  else
    return 0
  fi
  unset DPKGRESULTTMP
  set -e
}

#usage: unTar format_z_j_lzma file_path files_to_extract
#NOTE: This function must always exist!
function unTar()
{
  TAR_OPT=$1
  TAR_FILE="$2"
  shift 2

  #TODO: option "-n" in "pv" will allow the usage of "dialog --gauge" :)
  case ${TAR_OPT} in
  z | j)
    pv ${TAR_FILE} 2>&4 | tar -x${TAR_OPT} $*
    ;;
  *)
    pv ${TAR_FILE} 2>&4 | tar --${TAR_OPT} -x $*
    ;;
  esac
}
