#!/bin/bash

#-- FIXING FUNCTIONS ------------------------------------------------------
#list of functions herein:

#global variables used by this script:
#   INST_SYSTEM - System variant for installation - defined in the master script
#   SCRIPT_WORKFOLDER - the folder where the main script's dependency files are located
#   OF_SHORT_VERSION - the short version of OpenFOAM to be installed. Example: 16x
#   OF_LONG_VERSION - the long version of OpenFOAM to be installed. Example: 1.6.x

#Code -----------------------------------------
echo "Sourcing fixing functions for OpenFOAM ${OF_LONG_VERSION}..."

#source system related script
if [ "x$INST_SYSTEM" != "x" -a "x$OF_SHORT_VERSION" != "x" ]; then
  . ${SCRIPT_WORKFOLDER}/${OF_MODULE_NAME}/${INST_SYSTEM}/fixes
else
  echo "The variable INST_SYSTEM and/or OF_SHORT_VERSION is/are empty and both are crucial to exist! Aborting execution."
  exit 1
fi

#-- FUNCTIONS -----------------------------------------------------

#FIXES ------
#NOTE: This function must always exist!
function apply_fixes()
{
  cd_openfoam #this is a precautionary measure

  #apply fixes associated with the system
  apply_fixes_system
}

