#!/bin/bash

#-- USER INTERFACE FUNCTIONS ------------------------------------------------------
#list of functions herein:
#   gcc_related_options()
#   check_options_sanity()

#global variables used by this script:
#   INST_SYSTEM - System variant for installation - defined in the master script
#   SCRIPT_WORKFOLDER - the work folder for the script (contains all of the dependencies of the script) - defined in the master script
#   OF_SHORT_VERSION - short version of OpenFOAM to be installed - defined in common/user_interface
#   INSTALLMODE   - option for the installation mode - defined in common/user_interface
#   GUI_BACKTITLE - The back title for the dialogs
#   USE_REPO_PV         - option for using the system's ParaView - defined in common/user_interface
#   USE_KITWARE_PV         - option for using the system's ParaView - defined in common/user_interface
#   BUILD_GCC           - option for doing a custom build of gcc - defined gcc_related_options()
#   BUILD_GCC_STRICT_64BIT - option for doing a custom build of gcc but only the 64bit version (no multilib) - defined gcc_related_options()
#   BUILD_QT            - option for building Qt - defined in common/user_interface
#   BUILD_PARAVIEW      - option for building ParaView - defined in common/user_interface
#   BUILD_PARAVIEW_WITH_GUI - option for building ParaView with GUI - defined in common/user_interface
#   BUILD_PARAVIEW_WITH_MPI - option for building ParaView with MPI - defined in common/user_interface
#   BUILD_PARAVIEW_WITH_PYTHON - option for building ParaView with Python - defined in common/user_interface
#   BUILD_PARAVIEW_WITH_OSMESA - option for building ParaView with OSMesa - defined in common/user_interface


#Code -----------------------------------------
echo "Sourcing User Interface functions for OpenFOAM ${OF_LONG_VERSION}..."

#source system related script
if [ "x$INST_SYSTEM" != "x" -a "x${SCRIPT_WORKFOLDER}" != "x" ]; then
  . ${SCRIPT_WORKFOLDER}/${OF_MODULE_NAME}/${INST_SYSTEM}/user_interface
else
  echo "The variable INST_SYSTEM and/or SCRIPT_WORKFOLDER is/are empty and they are crucial to exist! Aborting execution."
  exit 1
fi


#GCC compiling settings
#NOTE: This function must always exist!
function gcc_related_options()
{

  if [ "x$USE_OF_GCC" == "xon" ]; then

    while : ; do
      GCCSETTINGSOPTS=$(dialog --stdout --separate-output \
      --backtitle "$GUI_BACKTITLE"         \
      --checklist "Choose Install settings: < Space to select ! >" 10 60 3 \
      1 "Build GCC? (otherwise use pre-compiled version)" $BUILD_GCC \
      2 "Use gcc 4.4 (pick only one version to build)" off \
      3 "Use gcc 4.5 (pick only one version to build)" on )

      if [ x"$?" == x"0" ]; then
        break;
      else
        cancel_installer
      fi
    done

    #Take care of unpack
    BUILD_GCC=off
    BUILD_GCC_STRICT_64BIT=off #Always off for OpenFOAM 1.7.x
    GCC_VERSION=45
    #remove any commas (happens in (Open)SuSE)
    GCCSETTINGSOPTS=`echo $GCCSETTINGSOPTS | sed 's="==g'`
    for setting in $GCCSETTINGSOPTS ; do
      if [ $setting == 1 ] ; then BUILD_GCC=on ; fi
      if [ $setting == 2 ] ; then GCC_VERSION=44 ; fi
      if [ $setting == 3 ] ; then GCC_VERSION=45 ; fi
    done

  else

    BUILD_GCC=off

  fi

}


#Check the sanity of the options
#NOTE: This function must always exist!
function check_options_sanity()
{
  #Check the sanity of the options, depending on the target system
  check_options_sanity_for_system

  if [ "x$INSTALLMODE" != "xcustom" ] && \
     ! [ "x$INSTALLMODE" == "xfresh" -a "x$USE_REPO_PV" == "xon" -o "x$USE_KITWARE_PV" == "xon" ]; then

    if [ "x$INSTALLMODE" == "xserver" ]; then
        BUILD_PARAVIEW=on
        BUILD_PARAVIEW_WITH_GUI=off
        BUILD_PARAVIEW_WITH_MPI=on
        dialog --sleep 6 --backtitle "$GUI_BACKTITLE"   \
        --title "Server Install settings" \
        --infobox "Installer in server install mode. \n ParaView will be build without GUI and with MPI support" 5 70
    fi

    #verifying ParaView Build options, just in case
    if [ "x$BUILD_PARAVIEW" == "xoff" ]; then
      if [ "x$BUILD_PARAVIEW_WITH_MPI" == "xon" -o "x$BUILD_PARAVIEW_WITH_PYTHON" == "xon" -o \
          "x$BUILD_PARAVIEW_WITH_GUI" == "xoff" -o "x$BUILD_QT" == "xon" ]; then
          BUILD_PARAVIEW=on
          dialog --sleep 6 --backtitle "$GUI_BACKTITLE"   \
          --title "Non-optional setting detected!" \
          --infobox "\nParaView will need to be built, since the pre-built version isn't enough for the chosen options." 10 70
      fi
    fi

    if [ "x$BUILD_PARAVIEW" == "xon" -a "x$BUILD_PARAVIEW_WITH_MPI" == "xoff" -a \
        "x$BUILD_PARAVIEW_WITH_GUI" == "xoff" ]; then
        BUILD_PARAVIEW_WITH_MPI=on
        dialog --sleep 6 --backtitle "$GUI_BACKTITLE"   \
        --title "Bad options detected!" \
        --infobox "\nParaView must be built with either MPI or GUI. Since you've defined both Off, will assume server mode and turn on MPI." 10 70
    fi

  fi
}

